from flask import Flask, render_template, request, jsonify, send_from_directory
import os
import random
import json
from datetime import datetime
from werkzeug.utils import secure_filename

app = Flask(__name__)
app.secret_key = 'growaimark-secret-key-2024'

# ==================== CONFIGURATION ====================
UPLOAD_FOLDER = 'static/uploads'
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif', 'webp'}
os.makedirs(UPLOAD_FOLDER, exist_ok=True)


def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


# ==================== TRANSLATOR TOOL IMPORT ====================
try:
    from tools.video_translator import VideoTranslator

    translator = VideoTranslator()
    print("✅ Video Translator imported successfully")
except ImportError as e:
    print(f"⚠️ Video Translator import failed: {e}")
    translator = None


# ==================== PAGE ROUTES ====================
@app.route('/')
def home():
    return render_template('index.html')


@app.route('/about')
def about():
    return render_template('about.html')


@app.route('/dashboard')
def dashboard():
    return render_template('dashboard.html')


@app.route('/portfolio')
def portfolio():
    return render_template('portfolio.html')


@app.route('/blog')
def blog():
    return render_template('blog.html')


@app.route('/admin')
def admin_panel():
    return render_template('admin.html')


@app.route('/blog/<slug>')
def blog_post(slug):
    return render_template('blog_post.html')


@app.route('/translator')
def translator_page():
    """Translator tool page"""
    if translator is None:
        return "Translator tool is currently unavailable. Please check back later.", 503
    return render_template('translator.html')


# ==================== AI CONTENT GENERATOR ====================
@app.route('/api/content/generate', methods=['POST'])
def generate_content():
    try:
        data = request.json
        topic = data.get('topic', '')
        content_type = data.get('type', 'blog')

        if not topic:
            return jsonify({'error': 'Topic is required'}), 400

        # Blog Post Template
        if content_type == 'blog':
            content = f"""<h2>Introduction to {topic.title()}</h2>
<p>{topic.title()} is transforming the digital marketing landscape in 2024. Businesses worldwide are leveraging this powerful strategy to achieve remarkable results.</p>

<h2>Why {topic.title()} Matters</h2>
<p>In today's competitive market, {topic.lower()} has become essential for business growth. Here's why:</p>
<ul>
<li><strong>Increased ROI:</strong> Companies using {topic.lower()} see up to 300% better returns</li>
<li><strong>Better Engagement:</strong> Audience engagement improves by 150%</li>
<li><strong>Scalable Solutions:</strong> Easy to scale as your business grows</li>
<li><strong>Data-Driven Decisions:</strong> Make informed choices based on real data</li>
</ul>

<h2>How to Get Started with {topic.title()}</h2>
<p>Follow these steps to implement {topic.lower()} effectively:</p>
<ol>
<li><strong>Research:</strong> Understand your audience and competitors</li>
<li><strong>Strategy:</strong> Develop a comprehensive plan</li>
<li><strong>Implementation:</strong> Execute your strategy systematically</li>
<li><strong>Analysis:</strong> Track metrics and optimize continuously</li>
</ol>

<h2>Best Practices for 2024</h2>
<p>Stay ahead with these proven strategies:</p>
<ul>
<li>Focus on quality over quantity</li>
<li>Leverage AI tools for automation</li>
<li>Monitor industry trends regularly</li>
<li>Test and iterate based on results</li>
</ul>

<h2>Conclusion</h2>
<p>{topic.title()} is not just a trend - it's the future of digital marketing. Start implementing these strategies today to stay ahead of the competition.</p>

<hr>
<p><em>Generated by GrowAIMark AI - 100% Free Tool</em></p>"""

        # Social Media Post
        elif content_type == 'social':
            content = f"""🔥 **{topic.title()}**: What You Need to Know!

Did you know? Businesses using {topic.lower()} see 3x better engagement!

💡 **Quick Tips:**
✅ Start with a clear strategy
✅ Track your metrics daily
✅ Engage with your audience
✅ Stay consistent

👇 Tag someone who needs to see this!

#DigitalMarketing #{topic.replace(' ', '')} #MarketingTips #BusinessGrowth #2024Trends

---
*Generated by GrowAIMark AI*"""

        # Email Newsletter
        elif content_type == 'email':
            content = f"""**Subject:** Unlock the Power of {topic.title()} 🚀

Hi there,

Are you ready to take your business to the next level? {topic.title()} can help you achieve:

✨ **Key Benefits:**
• 300% increase in engagement
• Better ROI than traditional methods
• Scalable solutions for growth
• Data-driven decision making

**Getting Started is Easy:**
1. Assess your current strategy
2. Identify improvement areas
3. Implement proven techniques
4. Monitor and optimize

Ready to transform your marketing? Let's connect!

Best regards,
GrowAIMark Team

P.S. Reply to this email for personalized advice!

---
*Generated by GrowAIMark AI*"""

        # Ad Copy
        else:
            content = f"""🚀 **Supercharge Your Business with {topic.title()}!**

✅ Increase Sales by 50%
✅ Get More Qualified Leads
✅ Save Time with Automation
✅ Scale Your Success

**Limited Time Offer:**
Get started today and receive a FREE consultation!

👉 Click Here to Learn More

#{topic.replace(' ', '')} #Marketing #BusinessGrowth #DigitalMarketing

---
*Generated by GrowAIMark AI*"""

        return jsonify({
            'success': True,
            'topic': topic,
            'type': content_type,
            'content': content,
            'word_count': len(content.split()),
            'message': '✨ AI Content Generated Successfully!'
        })

    except Exception as e:
        return jsonify({'error': str(e)}), 500


# ==================== YOUTUBE SEO OPTIMIZER ====================
@app.route('/api/youtube/seo', methods=['POST'])
def youtube_seo():
    try:
        data = request.json
        title = data.get('title', '')

        if not title:
            return jsonify({'error': 'Video title is required'}), 400

        optimized_titles = [
            f"{title} - Complete Guide 2024",
            f"How to {title} Like a Pro (Step by Step)",
            f"{title} Tutorial: Beginner to Advanced",
            f"Best {title} Tips You Need to Know",
            f"{title} for Beginners - Full Course",
            f"{title}: The Ultimate Guide",
            f"Top 10 {title} Strategies That Work"
        ]

        tags = [
            title.lower(),
            f"{title.lower()} tutorial",
            f"{title.lower()} guide",
            "digital marketing",
            "SEO tips",
            "marketing strategy",
            "business growth",
            "online marketing",
            "social media marketing"
        ]

        optimized_desc = f"""{title} - Complete Guide 2024

📌 In this video, you'll learn:
✅ What is {title}
✅ Why it matters for your business
✅ Step-by-step implementation
✅ Common mistakes to avoid
✅ Pro tips for better results

⏰ Timestamps:
0:00 - Introduction
1:30 - What is {title}
3:45 - Key Benefits
6:20 - How to Implement
10:00 - Pro Tips
12:30 - Common Mistakes
15:00 - Conclusion

🔗 Resources Mentioned:
👉 Free Marketing Tools: https://growaimark.com/dashboard
👉 SEO Analyzer: https://growaimark.com/dashboard
👉 Keyword Research Tool: https://growaimark.com/dashboard

👍 Like, Subscribe & Share for more marketing tips!

🔔 Turn on notifications so you never miss an update!

#marketing #{title.lower().replace(' ', '')} #seo #digitalmarketing #businesstips #2024trends"""

        return jsonify({
            'success': True,
            'optimized_titles': optimized_titles,
            'optimized_description': optimized_desc,
            'tags': tags,
            'message': '🎬 YouTube SEO Optimized Successfully!'
        })

    except Exception as e:
        return jsonify({'error': str(e)}), 500


# ==================== CONTENT CALENDAR ====================
@app.route('/api/calendar/generate', methods=['POST'])
def generate_calendar():
    try:
        data = request.json
        niche = data.get('niche', 'marketing')

        content_ideas = {
            'marketing': [
                "Share a case study of your best marketing campaign",
                "Post 5 marketing statistics with insights",
                "Behind the scenes of your daily work",
                "Client success story (with permission)",
                "Marketing tip of the day series",
                "Ask followers about their biggest challenge",
                "Recommended marketing tools and resources"
            ],
            'seo': [
                "SEO myth vs fact: Debunk common misconceptions",
                "How to find low-competition keywords",
                "Backlink building strategies that work",
                "Local SEO tips for small businesses",
                "Technical SEO checklist for beginners",
                "SEO tools comparison and review",
                "Core Web Vitals optimization guide"
            ],
            'social': [
                "Engagement boosting strategies",
                "Content calendar template download",
                "Best times to post on each platform",
                "Hashtag strategy for more reach",
                "Video content ideas that convert",
                "Instagram Reels tips and tricks",
                "User-generated content campaigns"
            ]
        }

        ideas = content_ideas.get(niche, content_ideas['marketing'])
        platforms = ['Instagram', 'LinkedIn', 'Twitter', 'Facebook', 'TikTok']
        times = ['9 AM', '12 PM', '3 PM', '6 PM', '8 PM']

        calendar = []
        for i in range(7):
            calendar.append({
                'day': i + 1,
                'date': f"Day {i + 1}",
                'idea': ideas[i % len(ideas)],
                'platform': platforms[i % len(platforms)],
                'best_time': times[i % len(times)]
            })

        return jsonify({
            'success': True,
            'niche': niche,
            'calendar': calendar,
            'message': '📅 7-Day Content Calendar Generated!'
        })

    except Exception as e:
        return jsonify({'error': str(e)}), 500


# ==================== COMPETITOR ANALYSIS ====================
@app.route('/api/competitor/analyze', methods=['POST'])
def analyze_competitor():
    try:
        data = request.json
        url = data.get('url', '')

        if not url:
            return jsonify({'error': 'URL is required'}), 400

        return jsonify({
            'success': True,
            'url': url,
            'metrics': {
                'domain_authority': random.randint(25, 85),
                'monthly_traffic': random.randint(5000, 500000),
                'top_keywords': [
                    'digital marketing services',
                    'SEO agency',
                    'social media management',
                    'PPC campaigns',
                    'content marketing',
                    'email marketing tools'
                ],
                'backlinks': random.randint(500, 8000),
                'social_followers': random.randint(1000, 150000),
                'pages_indexed': random.randint(50, 5000)
            },
            'strengths': [
                "Strong domain authority",
                "Good social media presence",
                "Regular content publishing schedule",
                "Quality backlink profile"
            ],
            'weaknesses': [
                "Mobile optimization needs improvement",
                "Page speed could be faster",
                "Limited backlink diversity"
            ],
            'opportunities': [
                "Target long-tail keywords",
                "Improve mobile experience",
                "Create more video content",
                "Build relationships with industry influencers"
            ],
            'message': '🔍 Competitor Analysis Complete!'
        })

    except Exception as e:
        return jsonify({'error': str(e)}), 500


# ==================== HASHTAG GENERATOR ====================
@app.route('/api/hashtags/generate', methods=['POST'])
def generate_hashtags():
    try:
        data = request.json
        topic = data.get('topic', '')

        if not topic:
            return jsonify({'error': 'Topic is required'}), 400

        hashtags = [
            f"#{topic.replace(' ', '')}",
            f"#{topic.replace(' ', '')}Tips",
            f"#{topic.replace(' ', '')}Strategy",
            f"#{topic.replace(' ', '')}2024",
            "#DigitalMarketing",
            "#MarketingTips",
            "#BusinessGrowth",
            "#SEO",
            "#SocialMediaMarketing",
            "#ContentMarketing",
            "#MarketingStrategy",
            "#SmallBusiness",
            "#GrowthHacking",
            "#MarketingTools",
            "#AIMarketing",
            "#ViralMarketing",
            "#BrandBuilding",
            "#LeadGeneration",
            "#OnlineBusiness",
            "#MarketingExpert"
        ]

        return jsonify({
            'success': True,
            'topic': topic,
            'hashtags': hashtags[:20],
            'popular_hashtags': hashtags[:5],
            'niche_hashtags': hashtags[5:10],
            'message': '#️⃣ Hashtags Generated Successfully!'
        })

    except Exception as e:
        return jsonify({'error': str(e)}), 500


# ==================== SEO ANALYZER ====================
@app.route('/api/seo/analyze', methods=['POST'])
def analyze_seo():
    try:
        data = request.json
        url = data.get('url', '')

        if not url:
            return jsonify({'error': 'URL is required'}), 400

        if not url.startswith('http'):
            url = 'https://' + url

        score = random.randint(65, 95)

        return jsonify({
            'success': True,
            'url': url,
            'score': score,
            'title': f'{url} - SEO Analysis Report',
            'meta_description': 'Comprehensive SEO analysis for better search rankings',
            'word_count': random.randint(300, 2500),
            'issues': [
                "Consider adding more internal links",
                "Improve page loading speed",
                "Add more high-quality backlinks"
            ],
            'recommendations': [
                "Write compelling meta descriptions",
                "Optimize images with alt text",
                "Create more long-form content",
                "Build quality backlinks"
            ],
            'message': '✨ SEO Analysis Complete!'
        })

    except Exception as e:
        return jsonify({'error': str(e)}), 500


# ==================== KEYWORD RESEARCH ====================
@app.route('/api/keywords/suggest', methods=['POST'])
def suggest_keywords():
    try:
        data = request.json
        keyword = data.get('keyword', '')

        if not keyword:
            return jsonify({'error': 'Keyword is required'}), 400

        keywords = [
            {'keyword': f'{keyword} services', 'volume': random.randint(500, 5000), 'competition': 'Medium',
             'cpc': round(random.uniform(1, 5), 2)},
            {'keyword': f'best {keyword}', 'volume': random.randint(800, 8000), 'competition': 'High',
             'cpc': round(random.uniform(2, 7), 2)},
            {'keyword': f'{keyword} agency', 'volume': random.randint(400, 4000), 'competition': 'Medium',
             'cpc': round(random.uniform(1.5, 4), 2)},
            {'keyword': f'{keyword} tools', 'volume': random.randint(600, 6000), 'competition': 'Low',
             'cpc': round(random.uniform(0.8, 3), 2)},
            {'keyword': f'affordable {keyword}', 'volume': random.randint(300, 3000), 'competition': 'Low',
             'cpc': round(random.uniform(0.5, 2.5), 2)},
            {'keyword': f'{keyword} expert', 'volume': random.randint(200, 2000), 'competition': 'Medium',
             'cpc': round(random.uniform(1.2, 3.5), 2)},
            {'keyword': f'{keyword} consultant', 'volume': random.randint(150, 1500), 'competition': 'Low',
             'cpc': round(random.uniform(1, 3), 2)},
            {'keyword': f'professional {keyword}', 'volume': random.randint(250, 2500), 'competition': 'Medium',
             'cpc': round(random.uniform(1.3, 3.8), 2)}
        ]

        return jsonify({
            'success': True,
            'keyword': keyword,
            'keywords': keywords,
            'message': '🔍 Keyword Research Complete!'
        })

    except Exception as e:
        return jsonify({'error': str(e)}), 500


# ==================== BACKLINK CHECKER ====================
@app.route('/api/backlink/analyze', methods=['POST'])
def analyze_backlinks():
    try:
        data = request.json
        url = data.get('url', '')

        if not url:
            return jsonify({'error': 'URL is required'}), 400

        return jsonify({
            'success': True,
            'url': url,
            'total_backlinks': random.randint(500, 10000),
            'referring_domains': random.randint(100, 1500),
            'dofollow_links': random.randint(300, 6000),
            'nofollow_links': random.randint(100, 3000),
            'top_backlinks': [
                {'domain': 'example1.com', 'authority': random.randint(40, 85), 'anchor_text': 'click here'},
                {'domain': 'example2.com', 'authority': random.randint(35, 75), 'anchor_text': 'learn more'},
                {'domain': 'example3.com', 'authority': random.randint(50, 90), 'anchor_text': 'check this'}
            ],
            'message': '🔗 Backlink Analysis Complete!'
        })

    except Exception as e:
        return jsonify({'error': str(e)}), 500


# ==================== RANK TRACKER ====================
@app.route('/api/rank/track', methods=['POST'])
def track_rank():
    try:
        data = request.json
        keyword = data.get('keyword', '')

        if not keyword:
            return jsonify({'error': 'Keyword is required'}), 400

        positions = [random.randint(5, 50) for _ in range(4)]

        return jsonify({
            'success': True,
            'keyword': keyword,
            'rankings': [
                {'date': 'Week 1', 'position': positions[0]},
                {'date': 'Week 2', 'position': positions[1]},
                {'date': 'Week 3', 'position': positions[2]},
                {'date': 'Week 4', 'position': positions[3]}
            ],
            'trend': 'improving' if positions[3] < positions[0] else 'declining',
            'current_position': positions[3],
            'improvement': positions[0] - positions[3],
            'message': '📈 Rank Tracking Complete!'
        })

    except Exception as e:
        return jsonify({'error': str(e)}), 500


# ==================== INTERNATIONAL SEO ====================
@app.route('/api/international/seo', methods=['POST'])
def international_seo():
    try:
        data = request.json
        url = data.get('url', '')
        country = data.get('country', 'us')

        if not url:
            return jsonify({'error': 'URL is required'}), 400

        country_names = {
            'us': 'USA', 'uk': 'United Kingdom', 'de': 'Germany',
            'fr': 'France', 'it': 'Italy', 'es': 'Spain', 'nl': 'Netherlands'
        }

        return jsonify({
            'success': True,
            'url': url,
            'country': country_names.get(country, 'Global'),
            'score': random.randint(65, 98),
            'global_rank': random.randint(10000, 5000000),
            'country_rank': random.randint(500, 100000),
            'organic_traffic': {
                'us': random.randint(5000, 100000),
                'uk': random.randint(2000, 50000),
                'eu': random.randint(10000, 200000)
            },
            'recommendations': [
                "Create country-specific landing pages",
                "Use hreflang tags for multilingual SEO",
                "Build backlinks from local domains",
                "Optimize for local search engines"
            ],
            'message': f'🌍 International SEO Analysis for {country_names.get(country, "Global")} Complete!'
        })

    except Exception as e:
        return jsonify({'error': str(e)}), 500


# ==================== CURRENCY CONVERTER ====================
@app.route('/api/currency/convert', methods=['POST'])
def currency_convert():
    try:
        data = request.json
        amount = data.get('amount', 100)
        from_curr = data.get('from', 'USD')
        to_curr = data.get('to', 'EUR')

        rates = {
            'USD': 1, 'EUR': 0.92, 'GBP': 0.79, 'PKR': 278, 'CAD': 1.35, 'AUD': 1.52, 'INR': 83.5
        }

        converted = amount * rates.get(to_curr, 1) / rates.get(from_curr, 1)

        return jsonify({
            'success': True,
            'amount': amount,
            'from': from_curr,
            'to': to_curr,
            'converted': round(converted, 2),
            'rate': round(rates.get(to_curr, 1) / rates.get(from_curr, 1), 4),
            'message': f'💱 Converted {amount} {from_curr} to {round(converted, 2)} {to_curr}'
        })

    except Exception as e:
        return jsonify({'error': str(e)}), 500


# ==================== MULTI-LANGUAGE CONTENT ====================
@app.route('/api/multilanguage/content', methods=['POST'])
def multilanguage_content():
    try:
        data = request.json
        topic = data.get('topic', '')
        language = data.get('language', 'en')

        if not topic:
            return jsonify({'error': 'Topic is required'}), 400

        languages = {
            'en': 'English', 'es': 'Spanish', 'fr': 'French',
            'de': 'German', 'it': 'Italian', 'nl': 'Dutch'
        }

        templates = {
            'en': f"📝 **Blog Post: {topic.title()}**\n\nIntroduction to {topic.title()}... This is your complete guide.",
            'es': f"📝 **Artículo: {topic.title()}**\n\nIntroducción a {topic.title()}... Esta es tu guía completa.",
            'fr': f"📝 **Article: {topic.title()}**\n\nIntroduction à {topic.title()}... Ceci est votre guide complet.",
            'de': f"📝 **Blogbeitrag: {topic.title()}**\n\nEinführung in {topic.title()}... Dies ist Ihre vollständige Anleitung.",
            'it': f"📝 **Articolo: {topic.title()}**\n\nIntroduzione a {topic.title()}... Questa è la tua guida completa.",
            'nl': f"📝 **Blogpost: {topic.title()}**\n\nInleiding tot {topic.title()}... Dit is je complete gids."
        }

        return jsonify({
            'success': True,
            'topic': topic,
            'language': languages.get(language, 'English'),
            'content': templates.get(language, templates['en']),
            'message': f'🌍 Content generated in {languages.get(language, "English")}!'
        })

    except Exception as e:
        return jsonify({'error': str(e)}), 500


# ==================== MARKET INSIGHTS ====================
@app.route('/api/market/insights', methods=['POST'])
def market_insights():
    try:
        data = request.json
        industry = data.get('industry', 'marketing')
        market = data.get('market', 'us')

        insights = {
            'us': {
                'market_size': '$450 Billion',
                'growth_rate': '12.5%',
                'top_trends': ['AI Marketing', 'Voice Search', 'Video Content', 'Personalization'],
                'consumer_behavior': 'High digital adoption, prefers mobile-first experiences'
            },
            'uk': {
                'market_size': '$120 Billion',
                'growth_rate': '10.2%',
                'top_trends': ['Sustainability', 'Social Commerce', 'Influencer Marketing'],
                'consumer_behavior': 'Privacy-conscious, values transparency'
            },
            'eu': {
                'market_size': '$380 Billion',
                'growth_rate': '11.8%',
                'top_trends': ['GDPR Compliance', 'Localization', 'Omnichannel Marketing'],
                'consumer_behavior': 'Multi-lingual, values data protection'
            }
        }

        data = insights.get(market, insights['us'])

        return jsonify({
            'success': True,
            'market': market.upper(),
            'industry': industry,
            'market_size': data['market_size'],
            'growth_rate': data['growth_rate'],
            'top_trends': data['top_trends'],
            'consumer_behavior': data['consumer_behavior'],
            'message': f'📊 {market.upper()} Market Insights for {industry}!'
        })

    except Exception as e:
        return jsonify({'error': str(e)}), 500


# ==================== TRANSLATOR API ROUTES ====================
@app.route('/api/translate/video', methods=['POST'])
def translate_video():
    """API endpoint for video translation"""
    if translator is None:
        return jsonify({'success': False, 'error': 'Translator not available'}), 503

    try:
        data = request.json
        url = data.get('url', '')
        target_lang = data.get('language', 'urdu')

        if not url:
            return jsonify({'success': False, 'error': 'URL is required'}), 400

        result = translator.process_video(url, target_lang)
        return jsonify(result)

    except Exception as e:
        return jsonify({'success': False, 'error': str(e)}), 500


@app.route('/api/translate/text', methods=['POST'])
def translate_text_api():
    """API endpoint for direct text translation"""
    if translator is None:
        return jsonify({'success': False, 'error': 'Translator not available'}), 503

    try:
        data = request.json
        text = data.get('text', '')
        target_lang = data.get('language', 'urdu')

        if not text:
            return jsonify({'success': False, 'error': 'Text is required'}), 400

        result = translator.translate_direct_text(text, target_lang)
        return jsonify(result)

    except Exception as e:
        return jsonify({'success': False, 'error': str(e)}), 500


@app.route('/api/translate/languages')
def get_languages():
    """Get supported languages"""
    languages = {
        'urdu': '🇵🇰 Urdu (Easy to understand)',
        'english': '🇬🇧 English',
        'hindi': '🇮🇳 Hindi',
        'arabic': '🇸🇦 Arabic',
        'french': '🇫🇷 French',
        'german': '🇩🇪 German',
        'spanish': '🇪🇸 Spanish',
        'turkish': '🇹🇷 Turkish',
        'bangla': '🇧🇩 Bangla',
        'pashto': '🇦🇫 Pashto'
    }
    return jsonify(languages)


# ==================== BLOG API ====================
BLOG_FILE = 'blog_posts.json'


def load_blog_posts():
    try:
        with open(BLOG_FILE, 'r', encoding='utf-8') as f:
            return json.load(f)
    except:
        return []


def save_blog_posts(posts):
    with open(BLOG_FILE, 'w', encoding='utf-8') as f:
        json.dump(posts, f, ensure_ascii=False, indent=2)


@app.route('/api/blog/posts')
def get_blog_posts():
    posts = load_blog_posts()
    return jsonify([{
        'id': p['id'],
        'title': p['title'],
        'slug': p['slug'],
        'category': p['category'],
        'date': p['date'],
        'read_time': p.get('read_time', '5 min read'),
        'image_url': p.get('image_url', ''),
        'excerpt': p['excerpt']
    } for p in posts])


@app.route('/api/blog/post/<slug>')
def get_blog_post(slug):
    posts = load_blog_posts()
    for post in posts:
        if post['slug'] == slug:
            return jsonify(post)
    return jsonify({'error': 'Post not found'}), 404


@app.route('/api/blog/post/<int:post_id>')
def get_blog_post_by_id(post_id):
    posts = load_blog_posts()
    for post in posts:
        if post['id'] == post_id:
            return jsonify(post)
    return jsonify({'error': 'Post not found'}), 404


@app.route('/api/blog/post/save', methods=['POST'])
def save_blog_post():
    data = request.json
    posts = load_blog_posts()

    if data.get('id'):
        for i, post in enumerate(posts):
            if post['id'] == data['id']:
                data['comments'] = post.get('comments', [])
                posts[i] = data
                break
    else:
        new_id = max([p['id'] for p in posts], default=0) + 1
        data['id'] = new_id
        data['comments'] = []
        posts.append(data)

    save_blog_posts(posts)
    return jsonify({'success': True, 'id': data['id']})


@app.route('/api/blog/post/<int:post_id>/delete', methods=['DELETE'])
def delete_blog_post(post_id):
    posts = load_blog_posts()
    posts = [p for p in posts if p['id'] != post_id]
    save_blog_posts(posts)
    return jsonify({'success': True})


@app.route('/api/blog/post/<slug>/comment', methods=['POST'])
def add_comment(slug):
    data = request.json
    posts = load_blog_posts()

    for post in posts:
        if post['slug'] == slug:
            comment = {
                'name': data.get('name', 'Reader'),
                'text': data.get('text', ''),
                'date': datetime.now().strftime('%B %d, %Y')
            }
            post.setdefault('comments', []).append(comment)
            save_blog_posts(posts)
            return jsonify({'success': True})

    return jsonify({'error': 'Post not found'}), 404


@app.route('/api/blog/upload-image', methods=['POST'])
def upload_blog_image():
    if 'image' not in request.files:
        return jsonify({'error': 'No image file'}), 400

    file = request.files['image']
    if file.filename == '':
        return jsonify({'error': 'No file selected'}), 400

    if file and allowed_file(file.filename):
        filename = secure_filename(file.filename)
        name, ext = os.path.splitext(filename)
        filename = f"{int(datetime.now().timestamp())}_{name}{ext}"
        filepath = os.path.join(UPLOAD_FOLDER, filename)
        file.save(filepath)

        image_url = f"/static/uploads/{filename}"
        return jsonify({'success': True, 'url': image_url})

    return jsonify({'error': 'Invalid file type'}), 400


# ==================== PRICING API ====================
@app.route('/api/pricing')
def get_pricing():
    return jsonify({
        'free': {
            'name': 'Free Forever',
            'price': 0,
            'daily_limit': 'Unlimited',
            'tools': ['All 10+ Tools'],
            'features': ['Unlimited Usage', 'No Credit Card Required', 'Full Access']
        }
    })


# ==================== USAGE CHECK ====================
@app.route('/api/usage/check')
def check_usage():
    return jsonify({
        'success': True,
        'plan': 'free',
        'limit': 'Unlimited',
        'message': 'All tools are completely free!'
    })


# ==================== RUN APP ====================
if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port, debug=True)