from flask import Flask, render_template, request, jsonify
import os
import random
import json

app = Flask(__name__)


# AI Content Generator (ChatGPT-like)
@app.route('/api/content/generate', methods=['POST'])
def generate_content():
    data = request.json
    topic = data.get('topic', '')
    content_type = data.get('type', 'blog')  # blog, social, email, ad

    templates = {
        'blog': f"""📝 **Blog Post: {topic.title()}**

**Introduction**
{topic.title()} is becoming increasingly important in today's digital landscape. Businesses are leveraging it to gain competitive advantage.

**Key Benefits**
1. Increased efficiency and productivity
2. Better ROI compared to traditional methods
3. Scalable solutions for growing businesses
4. Data-driven decision making

**How to Get Started**
Start by analyzing your current needs. Then implement a phased approach to ensure smooth adoption. Track metrics to measure success.

**Conclusion**
{topic.title()} is not just a trend - it's the future. Start implementing today to stay ahead of the competition.

---
*Generated by GrowAIMark AI*""",

        'social': f"""🔥 **{topic.title()}**: What you need to know!

✨ Did you know? Businesses using {topic} see 3x better results!

💡 Pro Tip: Start small, measure results, scale what works.

👇 Tag someone who needs to know this!

#DigitalMarketing #{topic.replace(' ', '')} #Growth #MarketingTips""",

        'email': f"""**Subject:** Unlock the Power of {topic.title()}

Hi there,

Are you ready to take your business to the next level? {topic.title()} can help you achieve:

✅ Higher engagement rates
✅ Better conversion metrics
✅ Sustainable growth

Start your journey today!

Best regards,
GrowAIMark Team

P.S. Want personalized advice? Reply to this email!""",

        'ad': f"""🚀 **Boost Your Business with {topic.title()}!**

✅ Increase sales by 50%
✅ Get more customers
✅ Save time & money

👉 Click here to learn more!

#Marketing #BusinessGrowth"""
    }

    return jsonify({
        'success': True,
        'topic': topic,
        'type': content_type,
        'content': templates.get(content_type, templates['blog']),
        'word_count': len(templates.get(content_type, templates['blog']).split()),
        'message': '✨ AI Content Generated - 100% Free!'
    })


# YouTube SEO Optimizer
@app.route('/api/youtube/seo', methods=['POST'])
def youtube_seo():
    data = request.json
    title = data.get('title', '')
    description = data.get('description', '')

    # Generate optimized title
    optimized_titles = [
        f"{title} - Complete Guide 2024",
        f"How to {title} Like a Pro",
        f"{title} Tutorial: Step by Step",
        f"Best {title} Tips You Need to Know",
        f"{title} for Beginners - Full Course"
    ]

    # Generate tags
    tags = [
        title.lower(),
        f"{title.lower()} tutorial",
        f"{title.lower()} guide",
        "digital marketing",
        "SEO tips",
        "marketing strategy"
    ]

    # Generate optimized description
    optimized_desc = f"""{title} - Full Guide 2024

In this video, you'll learn:
✅ What is {title}
✅ Why it matters for your business
✅ Step-by-step implementation
✅ Common mistakes to avoid
✅ Pro tips for better results

📌 Timestamps:
0:00 - Introduction
1:30 - What is {title}
3:45 - Key Benefits
6:20 - How to Implement
10:00 - Pro Tips
12:30 - Conclusion

🔗 Resources Mentioned:
👉 GrowAIMark Tools: https://growaimark.com
👉 Free Marketing Guide: [Link]

👍 Like, Subscribe & Share for more marketing tips!

#marketing #{title.lower().replace(' ', '')} #seo #digitalmarketing"""

    return jsonify({
        'success': True,
        'optimized_titles': optimized_titles,
        'optimized_description': optimized_desc,
        'tags': tags,
        'message': '🎬 YouTube SEO Optimized!'
    })


# Social Media Content Calendar
@app.route('/api/calendar/generate', methods=['POST'])
def generate_calendar():
    data = request.json
    niche = data.get('niche', 'marketing')
    days = data.get('days', 7)

    content_ideas = {
        'marketing': [
            "Share a recent marketing case study",
            "Post a marketing statistic with insight",
            "Create a 'behind the scenes' of your work",
            "Share a client success story",
            "Post a marketing tip of the day",
            "Ask followers about their biggest marketing challenge",
            "Share a useful marketing tool recommendation"
        ],
        'seo': [
            "SEO myth vs fact post",
            "Share a ranking tip",
            "Post about keyword research",
            "Backlink building strategy",
            "Local SEO tips",
            "Technical SEO checklist",
            "SEO tools comparison"
        ],
        'social': [
            "Engagement boosting strategy",
            "Content calendar template",
            "Best time to post guide",
            "Hashtag strategy",
            "Video content tips",
            "Stories ideas",
            "User-generated content campaign"
        ]
    }

    calendar = []
    for i in range(days):
        calendar.append({
            'day': i + 1,
            'date': f"Day {i + 1}",
            'idea': content_ideas.get(niche, content_ideas['marketing'])[i % 7],
            'platform': ['Instagram', 'LinkedIn', 'Twitter', 'Facebook'][i % 4],
            'best_time': ['9 AM', '12 PM', '3 PM', '6 PM'][i % 4]
        })

    return jsonify({
        'success': True,
        'niche': niche,
        'calendar': calendar,
        'message': '📅 Content Calendar Generated!'
    })


# Competitor Analysis Tool
@app.route('/api/competitor/analyze', methods=['POST'])
def analyze_competitor():
    data = request.json
    competitor_url = data.get('url', '')

    # Simulate competitor analysis
    return jsonify({
        'success': True,
        'url': competitor_url,
        'metrics': {
            'domain_authority': random.randint(30, 85),
            'monthly_traffic': random.randint(10000, 500000),
            'top_keywords': [
                'digital marketing services',
                'SEO agency',
                'social media management',
                'PPC campaigns',
                'content marketing'
            ],
            'backlinks': random.randint(500, 5000),
            'social_followers': random.randint(5000, 100000)
        },
        'strengths': [
            "Strong domain authority",
            "Good social media presence",
            "Regular content publishing"
        ],
        'weaknesses': [
            "Low mobile optimization",
            "Slow page speed",
            "Limited backlink diversity"
        ],
        'opportunities': [
            "Target long-tail keywords",
            "Improve mobile experience",
            "Create video content"
        ],
        'message': '🔍 Competitor Analysis Complete!'
    })


# Hashtag Generator
@app.route('/api/hashtags/generate', methods=['POST'])
def generate_hashtags():
    data = request.json
    topic = data.get('topic', '')

    hashtags = [
        f"#{topic.replace(' ', '')}",
        f"#{topic.replace(' ', '')}Tips",
        f"#{topic.replace(' ', '')}Strategy",
        "#DigitalMarketing",
        "#MarketingTips",
        "#BusinessGrowth",
        "#SEO",
        "#SocialMediaMarketing",
        "#ContentMarketing",
        "#MarketingStrategy",
        "#SmallBusiness",
        "#GrowthHacking",
        "#MarketingTools",
        "#AI"
    ]

    return jsonify({
        'success': True,
        'topic': topic,
        'hashtags': hashtags[:15],
        'popular_hashtags': hashtags[:5],
        'niche_hashtags': hashtags[5:10],
        'message': '#️⃣ Hashtags Generated!'
    })