from flask import Flask, render_template, request, jsonify
import os
import random

app = Flask(__name__)


# ==================== HOME & PAGES ====================
@app.route('/')
def home():
    return render_template('index.html')


@app.route('/about')
def about():
    return render_template('about.html')


@app.route('/dashboard')
def dashboard():
    return render_template('dashboard.html')


# ==================== TOOL 1: SEO ANALYZER ====================
@app.route('/api/seo/analyze', methods=['POST'])
def analyze_seo():
    data = request.json
    url = data.get('url', '')

    return jsonify({
        'success': True,
        'url': url,
        'score': random.randint(65, 95),
        'title': f'{url} - Website Analysis',
        'meta_description': 'Comprehensive SEO analysis for better rankings',
        'word_count': random.randint(300, 1500),
        'issues': ['Consider adding more keywords', 'Improve page loading speed', 'Add internal links'],
        'recommendations': ['Write compelling meta descriptions', 'Optimize images', 'Add more content'],
        'message': '✨ Free SEO Tool - No limits!'
    })


# ==================== TOOL 2: AI CONTENT GENERATOR ====================
@app.route('/api/content/generate', methods=['POST'])
def generate_content():
    data = request.json
    topic = data.get('topic', '')
    content_type = data.get('type', 'blog')

    templates = {
        'blog': f"""📝 **Blog Post: {topic.title()}**

**Introduction**
{topic.title()} is becoming increasingly important in today's digital landscape. Businesses are leveraging it to gain competitive advantage.

**Key Benefits**
1. Increased efficiency and productivity
2. Better ROI compared to traditional methods
3. Scalable solutions for growing businesses
4. Data-driven decision making

**How to Get Started**
Start by analyzing your current needs. Then implement a phased approach to ensure smooth adoption. Track metrics to measure success.

**Conclusion**
{topic.title()} is not just a trend - it's the future. Start implementing today to stay ahead of the competition.

---
*Generated by GrowAIMark AI*""",

        'social': f"""🔥 **{topic.title()}**: What you need to know!

✨ Did you know? Businesses using {topic} see 3x better results!

💡 Pro Tip: Start small, measure results, scale what works.

👇 Tag someone who needs to know this!

#DigitalMarketing #{topic.replace(' ', '')} #Growth #MarketingTips""",

        'email': f"""**Subject:** Unlock the Power of {topic.title()}

Hi there,

Are you ready to take your business to the next level? {topic.title()} can help you achieve:

✅ Higher engagement rates
✅ Better conversion metrics
✅ Sustainable growth

Start your journey today!

Best regards,
GrowAIMark Team

P.S. Want personalized advice? Reply to this email!""",

        'ad': f"""🚀 **Boost Your Business with {topic.title()}!**

✅ Increase sales by 50%
✅ Get more customers
✅ Save time & money

👉 Click here to learn more!

#Marketing #BusinessGrowth"""
    }

    return jsonify({
        'success': True,
        'topic': topic,
        'type': content_type,
        'content': templates.get(content_type, templates['blog']),
        'word_count': len(templates.get(content_type, templates['blog']).split()),
        'message': '✨ AI Content Generated - 100% Free!'
    })


# ==================== TOOL 3: YOUTUBE SEO OPTIMIZER ====================
@app.route('/api/youtube/seo', methods=['POST'])
def youtube_seo():
    data = request.json
    title = data.get('title', '')

    optimized_titles = [
        f"{title} - Complete Guide 2024",
        f"How to {title} Like a Pro",
        f"{title} Tutorial: Step by Step",
        f"Best {title} Tips You Need to Know",
        f"{title} for Beginners - Full Course"
    ]

    tags = [
        title.lower(),
        f"{title.lower()} tutorial",
        f"{title.lower()} guide",
        "digital marketing",
        "SEO tips",
        "marketing strategy"
    ]

    optimized_desc = f"""{title} - Full Guide 2024

In this video, you'll learn:
✅ What is {title}
✅ Why it matters for your business
✅ Step-by-step implementation
✅ Common mistakes to avoid
✅ Pro tips for better results

📌 Timestamps:
0:00 - Introduction
1:30 - What is {title}
3:45 - Key Benefits
6:20 - How to Implement
10:00 - Pro Tips
12:30 - Conclusion

🔗 Resources Mentioned:
👉 GrowAIMark Tools: https://growaimark.com
👉 Free Marketing Guide: [Link]

👍 Like, Subscribe & Share for more marketing tips!

#marketing #{title.lower().replace(' ', '')} #seo #digitalmarketing"""

    return jsonify({
        'success': True,
        'optimized_titles': optimized_titles,
        'optimized_description': optimized_desc,
        'tags': tags,
        'message': '🎬 YouTube SEO Optimized!'
    })


# ==================== TOOL 4: CONTENT CALENDAR ====================
@app.route('/api/calendar/generate', methods=['POST'])
def generate_calendar():
    data = request.json
    niche = data.get('niche', 'marketing')
    days = data.get('days', 7)

    content_ideas = {
        'marketing': [
            "Share a recent marketing case study",
            "Post a marketing statistic with insight",
            "Create a 'behind the scenes' of your work",
            "Share a client success story",
            "Post a marketing tip of the day",
            "Ask followers about their biggest marketing challenge",
            "Share a useful marketing tool recommendation"
        ],
        'seo': [
            "SEO myth vs fact post",
            "Share a ranking tip",
            "Post about keyword research",
            "Backlink building strategy",
            "Local SEO tips",
            "Technical SEO checklist",
            "SEO tools comparison"
        ],
        'social': [
            "Engagement boosting strategy",
            "Content calendar template",
            "Best time to post guide",
            "Hashtag strategy",
            "Video content tips",
            "Stories ideas",
            "User-generated content campaign"
        ]
    }

    calendar = []
    ideas = content_ideas.get(niche, content_ideas['marketing'])
    platforms = ['Instagram', 'LinkedIn', 'Twitter', 'Facebook']
    times = ['9 AM', '12 PM', '3 PM', '6 PM']

    for i in range(days):
        calendar.append({
            'day': i + 1,
            'date': f"Day {i + 1}",
            'idea': ideas[i % len(ideas)],
            'platform': platforms[i % len(platforms)],
            'best_time': times[i % len(times)]
        })

    return jsonify({
        'success': True,
        'niche': niche,
        'calendar': calendar,
        'message': '📅 Content Calendar Generated!'
    })


# ==================== TOOL 5: COMPETITOR ANALYSIS ====================
@app.route('/api/competitor/analyze', methods=['POST'])
def analyze_competitor():
    data = request.json
    competitor_url = data.get('url', '')

    return jsonify({
        'success': True,
        'url': competitor_url,
        'metrics': {
            'domain_authority': random.randint(30, 85),
            'monthly_traffic': random.randint(10000, 500000),
            'top_keywords': [
                'digital marketing services',
                'SEO agency',
                'social media management',
                'PPC campaigns',
                'content marketing'
            ],
            'backlinks': random.randint(500, 5000),
            'social_followers': random.randint(5000, 100000)
        },
        'strengths': [
            "Strong domain authority",
            "Good social media presence",
            "Regular content publishing"
        ],
        'weaknesses': [
            "Low mobile optimization",
            "Slow page speed",
            "Limited backlink diversity"
        ],
        'opportunities': [
            "Target long-tail keywords",
            "Improve mobile experience",
            "Create video content"
        ],
        'message': '🔍 Competitor Analysis Complete!'
    })


# ==================== TOOL 6: HASHTAG GENERATOR ====================
@app.route('/api/hashtags/generate', methods=['POST'])
def generate_hashtags():
    data = request.json
    topic = data.get('topic', '')

    hashtags = [
        f"#{topic.replace(' ', '')}",
        f"#{topic.replace(' ', '')}Tips",
        f"#{topic.replace(' ', '')}Strategy",
        "#DigitalMarketing",
        "#MarketingTips",
        "#BusinessGrowth",
        "#SEO",
        "#SocialMediaMarketing",
        "#ContentMarketing",
        "#MarketingStrategy",
        "#SmallBusiness",
        "#GrowthHacking",
        "#MarketingTools",
        "#AI"
    ]

    return jsonify({
        'success': True,
        'topic': topic,
        'hashtags': hashtags[:15],
        'popular_hashtags': hashtags[:5],
        'niche_hashtags': hashtags[5:10],
        'message': '#️⃣ Hashtags Generated!'
    })


# ==================== TOOL 7: KEYWORD RESEARCH ====================
@app.route('/api/keywords/suggest', methods=['POST'])
def suggest_keywords():
    data = request.json
    keyword = data.get('keyword', '')

    return jsonify({
        'success': True,
        'keyword': keyword,
        'keywords': [
            {'keyword': f'{keyword} services', 'volume': random.randint(300, 1500), 'competition': 'Medium',
             'cpc': round(random.uniform(1, 5), 2)},
            {'keyword': f'best {keyword}', 'volume': random.randint(500, 2000), 'competition': 'High',
             'cpc': round(random.uniform(2, 6), 2)},
            {'keyword': f'{keyword} agency', 'volume': random.randint(400, 1200), 'competition': 'Medium',
             'cpc': round(random.uniform(1.5, 4), 2)},
            {'keyword': f'{keyword} tools', 'volume': random.randint(300, 1000), 'competition': 'Low',
             'cpc': round(random.uniform(0.8, 3), 2)},
            {'keyword': f'affordable {keyword}', 'volume': random.randint(200, 800), 'competition': 'Low',
             'cpc': round(random.uniform(0.5, 2.5), 2)}
        ],
        'message': '🔥 Free Keyword Research - Unlimited!'
    })


# ==================== TOOL 8: BACKLINK CHECKER ====================
@app.route('/api/backlink/analyze', methods=['POST'])
def analyze_backlinks():
    data = request.json
    url = data.get('url', '')

    return jsonify({
        'success': True,
        'url': url,
        'total_backlinks': random.randint(500, 5000),
        'referring_domains': random.randint(100, 800),
        'dofollow_links': random.randint(200, 3000),
        'top_backlinks': [
            {'domain': 'example.com', 'authority': random.randint(40, 80)},
            {'domain': 'blogger.com', 'authority': random.randint(50, 85)},
            {'domain': 'news.com', 'authority': random.randint(45, 75)}
        ],
        'message': '🔗 Free Backlink Analysis!'
    })


# ==================== TOOL 9: RANK TRACKER ====================
@app.route('/api/rank/track', methods=['POST'])
def track_rank():
    data = request.json
    keyword = data.get('keyword', '')

    return jsonify({
        'success': True,
        'keyword': keyword,
        'rankings': [
            {'date': 'Day 1', 'position': random.randint(20, 35)},
            {'date': 'Day 7', 'position': random.randint(15, 25)},
            {'date': 'Day 14', 'position': random.randint(10, 18)},
            {'date': 'Day 30', 'position': random.randint(5, 12)}
        ],
        'trend': 'improving',
        'message': '📈 Free Rank Tracking!'
    })


# ==================== PRICING API ====================
@app.route('/api/pricing')
def get_pricing():
    return jsonify({
        'free': {
            'name': 'Free Forever',
            'price': 0,
            'daily_limit': 'Unlimited',
            'tools': ['All 8 Tools'],
            'features': ['Unlimited Usage', 'No Credit Card Required']
        }
    })


if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port, debug=True)