# Generated by Django 6.0 on 2025-12-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(default='Marketing', max_length=50)),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
                ('author', models.CharField(default='GrowAiMark Team', max_length=100)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
    ]
